import { styleTags, tags as t } from "@lezer/highlight";
export const highlighting = styleTags({
    String: t.string,
    Number: t.number,
    Boolean: t.bool,
    Nil: t.null,
    PropertyName: t.propertyName,
    TemplateString: t.string,
    "extern var const": t.definitionKeyword,
    "include break continue enum class switch while for fork return": t.keyword,
    "new": t.special(t.keyword),
    "List Map Set": t.list,
    ",": t.separator,
    "[ ]": t.bracket,
    "{ }": t.brace,
    "( ) |" : t.paren,
    '< <= > >= == "!="': t.compareOperator,
    "if else and or": t.logicOperator,
    '+ - "/" "*" "+=" "-=" "/=" "*="': t.arithmeticOperator,
    Equal: t.definitionOperator,
    DotDot: t.arithmeticOperator,
    Comment: t.lineComment,
    Choice: t.controlOperator,
    BackUp: t.controlOperator,
    BoughName: t.controlKeyword,
    Speaker: t.name,
    Tag: t.tagName,
});

